name: Update Current Month Data

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:      # manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      # Step 4: Install Chromium & ChromeDriver
      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      # Step 5: Run scraper
      - name: Run scraper
        run: python fetch_data.py

      # Step 6: Commit & Push transactions.json using PAT
      - name: Commit & Push transactions.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add transactions.json
          git diff --cached --quiet || git commit -m "Update current month transactions"

          # Detect current branch
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

          # Push using Personal Access Token
          git push https://x-access-token:${{ secrets.MY_PAT }}@github.com/${{ github.repository }}.git $CURRENT_BRANCH
