name: Update Current Month Data

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:  # allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python fetch_data.py

      - name: Commit & Push transactions.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add transactions.json
          git diff --cached --quiet || git commit -m "Update current month transactions"
          git push
